#include "protocol_def.hpp"

#include <cstdio>
#include <fstream>
#include <map>
#include <string>
#include <type_traits>
#include <vector>

// ── collected metadata ──────────────────────────────────────────────────────

struct collected_field {
    std::string name;
    int         bit_width;
    int         bit_offset;
    std::string depends_on;
    int         match_value = 0;
};

struct collected_module {
    std::string name;
    std::string header;
    bool        needs_data       = false;
    int         max_connections  = 0;
};

static std::vector<collected_field>  g_fields;
static std::vector<collected_module> g_modules;
static int                           g_total_header_bits = 0;

// ── SFINAE detectors ────────────────────────────────────────────────────────

template <typename M, typename = void> struct has_needs_data : std::false_type {};
template <typename M>
struct has_needs_data<M, std::void_t<decltype(M::needs_data)>> : std::true_type {};

template <typename M>
std::enable_if_t<has_needs_data<M>::value>
read_needs_data(collected_module& cm) { cm.needs_data = M::needs_data; }
template <typename M>
std::enable_if_t<!has_needs_data<M>::value>
read_needs_data(collected_module&) {}

template <typename M, typename = void> struct has_max_conn : std::false_type {};
template <typename M>
struct has_max_conn<M, std::void_t<decltype(M::max_connections)>> : std::true_type {};

template <typename M>
std::enable_if_t<has_max_conn<M>::value>
read_max_conn(collected_module& cm) { cm.max_connections = M::max_connections; }
template <typename M>
std::enable_if_t<!has_max_conn<M>::value>
read_max_conn(collected_module&) {}

// ── field collection ────────────────────────────────────────────────────────

template <typename M>
void collect_module() {
    for (const auto& f : M::fields) {
        if (f.bit_width > 0) {
            collected_field cf;
            cf.name        = f.name;
            cf.bit_width   = f.bit_width;
            cf.bit_offset  = g_total_header_bits;
            cf.depends_on  = f.depends_on ? f.depends_on : "";
            cf.match_value = f.match_value;
            g_fields.push_back(cf);
            g_total_header_bits += f.bit_width;
        }
    }
    collected_module cm;
    cm.name   = M::name;
    cm.header = M::header;
    read_needs_data<M>(cm);
    read_max_conn<M>(cm);
    g_modules.push_back(std::move(cm));
}

template <typename... Ts>
void collect_all(nb::type_list<Ts...>) {
    (collect_module<Ts>(), ...);
}

// ── helpers ─────────────────────────────────────────────────────────────────

static const std::string INDENT = "    ";
static const char* BANNER = "// Auto-generated by net-blocks-hls2 code generator.  Do not edit.\n\n";

static int header_beats() {
    return (g_total_header_bits + protocol_data_width - 1) / protocol_data_width;
}

// Split fields into groups for conditional extraction.
// Root fields (no depends_on) come first.
// Then conditional groups keyed by (parent_name, match_value).
struct cond_group {
    std::string parent;
    int         match_val;
    int         parent_offset;  // bit offset of the parent field
    std::vector<const collected_field*> fields;
};

static void build_cond_groups(std::vector<const collected_field*>& roots,
                              std::vector<cond_group>& groups) {
    std::map<std::string, int> field_offsets;
    for (auto& f : g_fields)
        field_offsets[f.name] = f.bit_offset;

    std::map<std::pair<std::string,int>, cond_group> gmap;

    for (auto& f : g_fields) {
        if (f.depends_on.empty()) {
            roots.push_back(&f);
        } else {
            auto key = std::make_pair(f.depends_on, f.match_value);
            auto& g = gmap[key];
            g.parent      = f.depends_on;
            g.match_val   = f.match_value;
            g.parent_offset = field_offsets[f.depends_on];
            g.fields.push_back(&f);
        }
    }
    for (auto& kv : gmap)
        groups.push_back(std::move(kv.second));
}

// ── header emitter ──────────────────────────────────────────────────────────

static void emit_h_header(std::ofstream& out) {
    out << BANNER;
    out << "#ifndef NB_HLS_GENERATED_H\n"
        << "#define NB_HLS_GENERATED_H\n\n"
        << "#include <hls_stream.h>\n"
        << "#include <ap_axi_sdata.h>\n"
        << "#include <ap_int.h>\n\n";

    out << "#define NB_DATA_WIDTH   " << protocol_data_width << "\n"
        << "#define NB_HEADER_BITS   " << g_total_header_bits << "\n"
        << "#define NB_HEADER_BEATS  " << header_beats() << "\n"
        << "#define NB_HEADER_WORDS  " << ((g_total_header_bits+15)/16) << "\n"
        << "#define NB_SHIFT_BITS    "
        << "((NB_HEADER_BITS) > (NB_DATA_WIDTH) ? (NB_HEADER_BITS) : (NB_DATA_WIDTH))\n\n";

    for (auto& m : g_modules)
        if (m.max_connections > 0)
            out << "#define NB_MAX_CONNECTIONS " << m.max_connections << "\n\n";

    out << "typedef ap_axiu<NB_DATA_WIDTH, 1, 0, 0> axis_word;\n"
        << "typedef hls::stream<axis_word> axis_stream;\n\n";

    out << R"(struct axis_wordi {
    ap_uint<NB_DATA_WIDTH> data;
    ap_uint<1>            last;
    axis_wordi() {}
    axis_wordi(const axis_word& aw) : data(aw.data), last(aw.last) {}
    operator axis_word() const {
        axis_word aw;
        aw.data = data;
        aw.last = last;
        aw.keep = -1;
        return aw;
    }
};
typedef hls::stream<axis_wordi> axis_streai;

)";

    for (auto& mod : g_modules)
        out << "#include \"" << mod.header << "\"\n";
    out << "\n";

    out << "struct nb_metadata {\n";
    for (auto& f : g_fields)
        out << INDENT << "ap_uint<" << f.bit_width << "> " << f.name << ";\n";
    out << "};\n\n";

    out << R"(void nb_parser(axis_stream& data_in, axis_streai& data_out,
                 hls::stream<nb_metadata>& meta_out);
)";

    for (auto& mod : g_modules) {
        out << "void " << mod.name << "_action(";
        if (mod.needs_data) {
            out << "hls::stream<nb_metadata>& meta_in,\n"
                << INDENT << "hls::stream<nb_metadata>& meta_out,\n"
                << INDENT << "axis_streai& data_in, axis_streai& data_out);\n";
        } else {
            out << "hls::stream<nb_metadata>& meta_in,\n"
                << INDENT << "hls::stream<nb_metadata>& meta_out);\n";
        }
    }

    out << R"(void nb_deparser(axis_streai& data_in, axis_stream& data_out,
                   hls::stream<nb_metadata>& meta_in);

void nb_hls_top(axis_stream& rx, axis_stream& tx);

)";
    out << "#endif // NB_HLS_GENERATED_H\n";
}

// ── source emitter ──────────────────────────────────────────────────────────
static void emit_field_extraction(std::ofstream& out, const std::string& prefix,
                                  bool from_shift_reg) {
    // ── root fields ──────────────────────────────────────────────────
    std::vector<const collected_field*> roots;
    std::vector<cond_group> groups;
    build_cond_groups(roots, groups);

    for (auto f : roots) {
        int hi = f->bit_offset + f->bit_width - 1;
        int lo = f->bit_offset;
        out << INDENT << INDENT << prefix << f->name
            << " = shift_buf.range(" << hi << ", " << lo << ");\n";
    }

    // ── conditional groups ───────────────────────────────────────────
    for (auto& g : groups) {
        int ph = g.parent_offset + 16 - 1;  // assume parent is a 16-bit field
        int pl = g.parent_offset;
        // Find the actual width of the parent field
        for (auto& f : g_fields) {
            // parent width is stored in the root fields; find it
        }
        // For simplicity emit a switch on the parent's 16-bit value
        out << INDENT << INDENT << "if (" << prefix << g.parent
            << " == " << g.match_val << ") {\n";
        for (auto f : g.fields) {
            int hi = f->bit_offset + f->bit_width - 1;
            int lo = f->bit_offset;
            out << INDENT << INDENT << INDENT << prefix << f->name
                << " = shift_buf.range(" << hi << ", " << lo << ");\n";
        }
        out << INDENT << INDENT << "}\n";
    }
}

static void emit_parser(std::ofstream& out) {
    int hbeats = header_beats();

    out << R"(void nb_parser(axis_stream& data_in, axis_streai& data_out,
                 hls::stream<nb_metadata>& meta_out) {
#pragma HLS PIPELINE II = 1
    enum State { HDR, PAY };
    static State state = HDR;
    static ap_uint<NB_SHIFT_BITS> shift_buf;
    static int shift_fill = 0;

    if (data_in.empty()) return;
    axis_word word = data_in.read();

    if (state == HDR) {
        shift_buf.range(shift_fill + NB_DATA_WIDTH - 1, shift_fill)
            = word.data;
        shift_fill += NB_DATA_WIDTH;

        if (shift_fill >= NB_HEADER_BITS) {
            nb_metadata m;
)";

    // Zero conditional fields before extraction (they are only set
    // inside the conditional if-blocks, so initialize them here).
    for (auto& f : g_fields)
        if (!f.depends_on.empty())
            out << INDENT << INDENT << INDENT
                << "m." << f.name << " = 0;\n";

    emit_field_extraction(out, "m.", false);

    out << R"(
            meta_out.write(m);
            shift_fill = 0;

            if (!word.last)
                state = PAY;
        }
    } else {
        if (word.last)
            state = HDR;
    }

    data_out.write(axis_wordi(word));
}

)";
}

static void emit_actions(std::ofstream& out) {
    for (auto& mod : g_modules) {
        out << "void " << mod.name << "_action(";
        if (mod.needs_data) {
            out << "hls::stream<nb_metadata>& meta_in,\n"
                << INDENT << "hls::stream<nb_metadata>& meta_out,\n"
                << INDENT << "axis_streai& data_in, axis_streai& data_out) {\n"
                << INDENT << "#pragma HLS PIPELINE II = 1\n"
                << INDENT << "nb::" << mod.name << "_module::process("
                << "meta_in, meta_out, data_in, data_out);\n"
                << "}\n\n";
        } else {
            out << "hls::stream<nb_metadata>& meta_in,\n"
                << INDENT << "hls::stream<nb_metadata>& meta_out) {\n"
                << INDENT << "#pragma HLS PIPELINE II = 1\n"
                << INDENT << "nb::" << mod.name << "_module::process("
                << "meta_in, meta_out);\n"
                << "}\n\n";
        }
    }
}

static void emit_deparser(std::ofstream& out) {
    out << R"(void nb_deparser(axis_streai& data_in, axis_stream& data_out,
                   hls::stream<nb_metadata>& meta_in) {
#pragma HLS PIPELINE II = 1
    // Single-phase: reads both data and meta in one call.
    // Meta FIFOs are depth=64 to avoid DATAFLOW deadlock.
    enum State { HDR, PAY };
    static State state = HDR;

    if (state == HDR) {
        axis_wordi wi = data_in.read();
        axis_word word = wi;
        nb_metadata m = meta_in.read();
)";

    for (auto& f : g_fields) {
        int hi = f.bit_offset + f.bit_width - 1;
        int lo = f.bit_offset;
        out << INDENT << INDENT
            << "word.data.range(" << hi << ", " << lo
            << ") = m." << f.name << ";\n";
    }

    out << R"(
        data_out.write(word);
        if (!word.last) state = PAY;
    } else {
        axis_wordi wi = data_in.read();
        data_out.write(axis_word(wi));
        if (wi.last) state = HDR;
    }
}

)";
}

static void emit_top_level(std::ofstream& out) {
    int n = static_cast<int>(g_modules.size());
    int data_count = 0;
    for (auto& m : g_modules) if (m.needs_data) ++data_count;

    out << "void nb_hls_top(axis_stream& rx, axis_stream& tx) {\n"
        << "#pragma HLS INTERFACE axis port = rx\n"
        << "#pragma HLS INTERFACE axis port = tx\n"
        << "#pragma HLS DATAFLOW\n\n";

    for (int d = 0; d <= data_count; ++d)
        out << INDENT << "axis_streai data_" << d << ";\n"
            << "#pragma HLS STREAM variable = data_" << d << " depth = 64\n";
    out << "\n";

    for (int i = 0; i <= n; ++i)
        out << INDENT << "hls::stream<nb_metadata> meta_" << i << ";\n"
            << "#pragma HLS STREAM variable = meta_" << i << " depth = 64\n";

    out << "\n" << INDENT << "nb_parser(rx, data_0, meta_0);\n";

    int data_idx = 0;
    for (int i = 0; i < n; ++i) {
        out << INDENT << g_modules[i].name << "_action(meta_" << i
            << ", meta_" << (i + 1);
        if (g_modules[i].needs_data) {
            out << ",\n" << INDENT << "         data_" << data_idx
                << ", data_" << (data_idx + 1);
            ++data_idx;
        }
        out << ");\n";
    }

    out << INDENT << "nb_deparser(data_" << data_idx
        << ", tx, meta_" << n << ");\n";
    out << "}\n";
}

// ── main ────────────────────────────────────────────────────────────────────

// Top-level dispatcher (must be after all emit_* definitions)
static void emit_h_source(std::ofstream& out) {
    out << BANNER;
    out << "#include \"nb_hls.h\"\n\n";
    emit_parser(out);
    emit_actions(out);
    emit_deparser(out);
    emit_top_level(out);
}

int main() {
    collect_all(protocol_modules{});

    fprintf(stderr, "gen_all: %zu fields, %zu modules, %d header bits\n",
            g_fields.size(), g_modules.size(), g_total_header_bits);

    if (g_fields.empty() && g_modules.empty())
        return 0;

    {
        std::ofstream h("output/nb_hls.h");
        if (!h) { fprintf(stderr, "cannot open nb_hls.h\n"); return 1; }
        emit_h_header(h);
        if (h.fail()) { fprintf(stderr, "fail writing nb_hls.h\n"); return 1; }
    }
    {
        std::ofstream s("output/nb_hls.cpp");
        if (!s) { fprintf(stderr, "cannot open nb_hls.cpp\n"); return 1; }
        emit_h_source(s);
        if (s.fail()) { fprintf(stderr, "fail writing nb_hls.cpp\n"); return 1; }
    }
    return 0;
}
