#include "protocol_def.hpp"

#include <fstream>
#include <string>
#include <vector>

// ── collected metadata ──────────────────────────────────────────────────────

struct collected_field {
    std::string name;
    int bit_width;
    int bit_offset;
};

struct collected_module {
    std::string name;
    std::string header;
};

static std::vector<collected_field>  g_fields;
static std::vector<collected_module> g_modules;
static int                           g_total_header_bits = 0;

template <typename M>
void collect_module() {
    for (const auto& f : M::fields) {
        if (f.bit_width > 0) {
            g_fields.push_back({f.name, f.bit_width, g_total_header_bits});
            g_total_header_bits += f.bit_width;
        }
    }
    g_modules.push_back({M::name, M::header});
}

template <typename... Ts>
void collect_all(nb::type_list<Ts...>) {
    (collect_module<Ts>(), ...);
}

// ── common strings ──────────────────────────────────────────────────────────

static const std::string INDENT = "    ";

static const char* BANNER =
    "// Auto-generated by net-blocks-hls2 code generator.  Do not edit.\n\n";

// ── header emitter ──────────────────────────────────────────────────────────

static void emit_h_header(std::ofstream& out) {
    out << BANNER;
    out << "#ifndef NB_HLS_GENERATED_H\n"
        << "#define NB_HLS_GENERATED_H\n\n"
        << "#include <hls_stream.h>\n"
        << "#include <ap_axi_sdata.h>\n"
        << "#include <ap_int.h>\n\n";

    out << "#define NB_DATA_WIDTH " << protocol_data_width << "\n\n";

    out << "typedef ap_axiu<NB_DATA_WIDTH, 1, 0, 0> axis_word;\n"
        << "typedef hls::stream<axis_word> axis_stream;\n\n";

    out << R"(struct axis_wordi {
    ap_uint<NB_DATA_WIDTH> data;
    ap_uint<1>            last;
    axis_wordi() {}
    axis_wordi(const axis_word& aw) : data(aw.data), last(aw.last) {}
    operator axis_word() const {
        axis_word aw;
        aw.data = data;
        aw.last = last;
        aw.keep = -1;
        return aw;
    }
};
typedef hls::stream<axis_wordi> axis_streai;

)";

    for (const auto& mod : g_modules) {
        out << "#include \"" << mod.header << "\"\n";
    }
    out << "\n";

    out << "struct nb_metadata {\n";
    for (const auto& f : g_fields) {
        out << INDENT << "ap_uint<" << f.bit_width << "> " << f.name << ";\n";
    }
    out << "};\n\n";

    out << R"(void nb_parser(axis_stream& data_in, axis_streai& data_out,
                 hls::stream<nb_metadata>& meta_out);
)";

    for (const auto& mod : g_modules) {
        out << "void " << mod.name << "_action(hls::stream<nb_metadata>& meta_in,\n"
            << INDENT << "hls::stream<nb_metadata>& meta_out);\n";
    }

    out << R"(void nb_deparser(axis_streai& data_in, axis_stream& data_out,
                   hls::stream<nb_metadata>& meta_in);

void nb_hls_top(axis_stream& rx, axis_stream& tx);

)";

    out << "#endif // NB_HLS_GENERATED_H\n";
}

// ── source emitter ──────────────────────────────────────────────────────────

static void emit_h_source(std::ofstream& out) {
    out << BANNER;
    out << "#include \"nb_hls.h\"\n\n";

    // parser
    out << R"(void nb_parser(axis_stream& data_in, axis_streai& data_out,
                 hls::stream<nb_metadata>& meta_out) {
#pragma HLS PIPELINE II = 1
    enum State { HEADER, PAYLOAD };
    static State state = HEADER;

    axis_word word = data_in.read();

    if (state == HEADER) {
        nb_metadata m;
)";

    for (const auto& f : g_fields) {
        int hi = f.bit_offset + f.bit_width - 1;
        int lo = f.bit_offset;
        out << INDENT << INDENT << "m." << f.name << " = word.data.range("
            << hi << ", " << lo << ");\n";
    }

    out << R"(
        meta_out.write(m);

        if (word.last)
            state = HEADER;
        else
            state = PAYLOAD;
    } else {
        if (word.last)
            state = HEADER;
    }

    data_out.write(axis_wordi(word));
}

)";

    // actions
    for (const auto& mod : g_modules) {
        out << "void " << mod.name << "_action(hls::stream<nb_metadata>& meta_in,\n"
            << INDENT << "hls::stream<nb_metadata>& meta_out) {\n"
            << INDENT << "#pragma HLS PIPELINE II = 1\n"
            << INDENT << "nb::" << mod.name << "_module::process(meta_in, meta_out);\n"
            << "}\n\n";
    }

    // deparser
    out << R"(void nb_deparser(axis_streai& data_in, axis_stream& data_out,
                   hls::stream<nb_metadata>& meta_in) {
#pragma HLS PIPELINE II = 1
    enum State { HEADER, PAYLOAD };
    static State state = HEADER;

    if (state == HEADER) {
        axis_wordi wi = data_in.read();
        axis_word  word = wi;
        nb_metadata m = meta_in.read();

)";

    for (const auto& f : g_fields) {
        int hi = f.bit_offset + f.bit_width - 1;
        int lo = f.bit_offset;
        out << INDENT << INDENT << "word.data.range(" << hi << ", " << lo
            << ") = m." << f.name << ";\n";
    }

    out << R"(
        data_out.write(word);

        if (!word.last)
            state = PAYLOAD;
    } else {
        axis_wordi wi = data_in.read();
        data_out.write(axis_word(wi));

        if (wi.last)
            state = HEADER;
    }
}

)";

    // top
    int n = static_cast<int>(g_modules.size());
    out << "void nb_hls_top(axis_stream& rx, axis_stream& tx) {\n"
        << "#pragma HLS INTERFACE axis port = rx\n"
        << "#pragma HLS INTERFACE axis port = tx\n"
        << "#pragma HLS DATAFLOW\n\n"
        << INDENT << "axis_streai data_after_parse;\n"
        << "#pragma HLS STREAM variable = data_after_parse depth = 64\n\n";

    for (int i = 0; i <= n; ++i) {
        out << INDENT << "hls::stream<nb_metadata> meta_" << i << ";\n"
            << "#pragma HLS STREAM variable = meta_" << i << " depth = 2\n";
    }

    out << "\n" << INDENT << "nb_parser(rx, data_after_parse, meta_0);\n";

    for (int i = 0; i < n; ++i) {
        out << INDENT << g_modules[i].name << "_action(meta_" << i
            << ", meta_" << (i + 1) << ");\n";
    }

    out << INDENT << "nb_deparser(data_after_parse, tx, meta_" << n << ");\n";
    out << "}\n";
}

// ── main ────────────────────────────────────────────────────────────────────

int main() {
    collect_all(protocol_modules{});

    if (g_fields.empty() && g_modules.empty()) {
        return 0;
    }

    {
        std::ofstream h("output/nb_hls.h");
        if (!h) return 1;
        emit_h_header(h);
        if (h.fail()) return 1;
    }

    {
        std::ofstream s("output/nb_hls.cpp");
        if (!s) return 1;
        emit_h_source(s);
        if (s.fail()) return 1;
    }

    return 0;
}
